server:
  port: 8090

spring:
  application:
    name: rococo-gateway

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    net.devh.boot.grpc: INFO
    org.springframework.boot.autoconfigure: INFO

rococo-userdata:
  client: rest

---
spring:
  config:
    activate:
      on-profile: 'local'
  autoconfigure:
    exclude:
      - 'org.springframework.cloud.vault.config.VaultAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultObservationAutoConfiguration'
      - 'org.springframework.cloud.vault.config.VaultReactiveAutoConfiguration'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
  graphql:
    graphiql:
      enabled: true

grpc:
  client:
    grpcCurrencyClient:
      address: 'static://localhost:8095'
      negotiationType: PLAINTEXT

rococo-artist:
  base-uri: 'http://127.0.0.1:8091'
rococo-geo:
  base-uri: 'http://127.0.0.1:8092'
rococo-museum:
  base-uri: 'http://127.0.0.1:8093'
rococo-painting:
  base-uri: 'http://127.0.0.1:8094'
rococo-userdata:
  base-uri: 'http://127.0.0.1:8089'
rococo-front:
  base-uri: 'http://127.0.0.1:3000'
rococo-gateway:
  base-uri: 'http://127.0.0.1:8090'
---
